# Generated by Django 5.1.15 on 2025-12-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
            ],
        ),
    ]
