# Generated by Django 5.1.13 on 2025-10-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_alter_orderitem_quantity_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='producto_categories', through='componentes.ProductCategory', to='componentes.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_manufacturer', to='componentes.manufacturer'),
        ),
    ]
